### ISSUE TITLE
Las historias de usuario de asignan a un milestone para priorizar la modelización de una parte de un problema u otro

### ISSUE THREAD

**Issue by JJ** [mariavallejo20/proyecto_mvo#13]
Asignar #3 #5 y #6 al milestone 0 no ayuda en absoluto a crear un producto mínimo, ni a centrarse en qué parte de la lógica de negocio se va a implementar primero. En un desarrollo de un producto, es esencial priorizar las historias de usuario, partiendo de las más simples, para llegar a las más complicadas (que se empaquetarán en un PMV más adelante).
Si pones las tres en el primer milestone, significa que cuando llegues al [segundo](https://github.com/mariavallejo20/proyecto_mvo/milestone/6) vas a tener que implementar la lógica de negocio de *todos* ellos.

**Comment by mariavallejo20** [comment]
De acuerdo, ya he modificado esto para implementar la lógica de negocio poco a poco y no de todos a la vez. Gracias por su aclaración. 🤗

**Comment by JJ** [comment]
Los issues siempre deben cerrarse con un commit o un PR. En este caso, posiblemente podrías hacer algún pequeño cambio en la documentación de los milestones (donde también puedes trabajar con #14 ) donde aclares eso. La documentación en el repo y en los ficheros deben estar sincronizados. Gracias en todo caso por contestar tan rápidamente.

**Comment by mariavallejo20** [comment]
Si, tengo que modificar la documentación relativa a los milestones, cerraré estos issues en ese commit. Gracias a usted. 🤗

**Comment by mariavallejo20** [comment]
No tengo muy claro como debo hacer yo el commit o el PR. ¿Debo abrir una nueva rama, relativa al objetivo 1, realizando ahí las modificaciones y así cerrar los issues? 🤔

**Comment by JJ** [comment]
> No tengo muy claro como debo hacer yo el commit o el PR. ¿Debo abrir una nueva rama, relativa al objetivo 1, realizando ahí las modificaciones y así cerrar los issues? thinking

Claro, ¿cómo si no?

Puedes hacerlo directamente con un cambio en main, claro, ya que esto no lo va a revisar nadie más que tú misma.
