### ISSUE TITLE
El milestone 1 no está en secuencia

### ISSUE THREAD

**Issue by JJ** [mariavallejo20/proyecto_mvo#14]
[Este milestone](https://github.com/mariavallejo20/proyecto_mvo/milestone/3) no está en la secuencia adecuada. Si es imprescindible tener un producto que obtenga los datos para programar la lógica de negocio, tendría que estar ahí. Como para la lógica de negocio sólo se necesitan ejemplos, sobra.
Disculpas por no haber hecho esto en la revisión de código correspondiente.
Os recuerdo que los milestones son lo que realmente tenéis que hacer en este proyecto. Para el objetivo 4 tendréis que completar el milestone 2. Si este milestone consideras que está en secuencia, *tendrás que programarlo antes o durante el objetivo 4*.
A partir de ahí, es tu decisión.

**Comment by mariavallejo20** [comment]
De acuerdo, por lo que me comentas comprendo que no es imprescindible a la hora de tener un producto, por tanto lo he eliminado de mi secuencia de milestones y lo modificaré en el fichero "milestones".

Gracias por su comentario.🤗
