### ISSUE TITLE
[M0 - Dev] Comenzar el objetivo 3 sin tener terminado el objetivo 2

### ISSUE THREAD

**Issue by mariavallejo20** [mariavallejo20/proyecto_mvo#21]
Abro este issue para ver cómo puedo comenzar a trabajar en el objetivo 3 sin tener terminado el objetivo 2 de mi proyecto.

**Comment by mariavallejo20** [comment]
He estado documentándome sobre los gestores de dependencias y tareas que puedo utilizar en mi proyecto (#19 #20), y ya tengo elegidos los que quiero utilizar. Sin embargo, no sé cómo hacer el objetivo 3 sin tener el objetivo 2, y me gustaría empezarlo ya que sé que es recomendable comenzar con el objetivo 3 ya para no ir atrasada. @JJ le solicito ayuda, si es posible, ya que aunque he leído lo que se ha comentado sobre esto en el grupo de Telegram, aún no me queda claro. 
Gracias 😊.

**Comment by mariavallejo20** [comment]
Para solucionar este problema, crearé una rama para el objetivo 3 en la que añadiré al archivo iv.yaml hasta ahora propuesto en el objetivo 2  y trabajaré sobre este.

**Comment by JJ** [comment]
Tendrás que clonar también el fichero al que hace referencia, o crear uno vacío. Como te dije [está en los errores frecuentes de esta semana](https://github.com/JJ/IV-22-23/blob/master/sesiones/semana-08.md#objetivo-3)
