### ISSUE TITLE
[M0 - Dev] Lenguaje de programación

### ISSUE THREAD

**Issue by martahuetem** [mariavallejo20/proyecto_mvo#7]
Hola @mariavallejo20 !
He creado este issue para concretar el lenguaje de programación en el te gustaría hacer tu proyecto. ¿Cuál tienes pensado? 🤔

**Comment by mariavallejo20** [comment]
Hola @martahuetem!! 
Teniendo en cuenta las características de mi proyecto he estado pensando en utilizar node.js o ruby, pero no me decido entre los dos. 
¿Qué piensas tú? ¿Te es indiferente trabajar sobre los dos lenguajes o tienes preferencia por alguno?🕵️‍♂️

**Comment by martahuetem** [comment]
Hola @mariavallejo20!!! 
Pues a mi me da igual la verdad. Al final tu eres la que vas a hacer el desarrollo del proyecto. Tira por aquello en lo que te sientas mas cómoda. 
Ya me dices por cual te decides. 💙

**Comment by mariavallejo20** [comment]
Hola @martahuetem!! He decidido utilizar node.js. 🤩

**Comment by martahuetem** [comment]
Hola @mariavallejo20!! Perfecto!!!
